### ISSUE TITLE
Code coverage testing

### ISSUE THREAD

**Issue by tomiorban96** [BME-MIT-IET/3TB-iet-2019#18]
Testing code coverage and adding new test cases for missing parts.

**Comment by tomiorban96** [comment]
Initial code coverage
![image](https://user-images.githubusercontent.com/26327843/57696645-84907900-7651-11e9-99ba-8e5934d564ba.png)

**Comment by tomiorban96** [comment]
Code coverage after adding a new testcase
![image](https://user-images.githubusercontent.com/26327843/57701182-b7d80580-765b-11e9-948e-d7df7dfdd107.png)

**Comment by iet-konczol** [comment]
Great work!
